# The app name, needs to be unique on Fly.io
app = "frixconfessions-backend"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "5000"

[build]
  builder = "dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
